import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/Link'

export default function Socialmedia() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portfolio | Karlgusta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">my Social Media!</a>
        </h1>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <p className={styles.description}>
          Join me.
        </p>

        <div className={styles.grid}>
          <a href="https://twitter.com/annoh_karlgusta" className={styles.card}>
            <h2>Twitter &rarr;</h2>
            <p>Twitter here.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>LinkedIn &rarr;</h2>
            <p>LinkedIn here.</p>
          </a>

        </div>

        <Link href="/">
            <a>
                <h4>&larr; Home</h4>
                <h6>Go back home.</h6>
            </a>
        </Link>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
